// Actions
export const DELETE_USER = 'USERS/DELETE_USER';
export const SEARCH_USER = 'USERS/SEARCH_USER';
export const SORT_USER = 'USERS/SORT_USER';
export const CHANGE_PAGE = 'USERS/CHANGE_PAGE';
export const CLEAR_SEARCH_FILTER = 'USERS/CLEAR_SEARCH_FILTER';
