export const DELETE_USER = 'USERS__DELETE_USER';
export const SEARCH_USER = 'USERS__SEARCH_USER';
export const SORT_USER = 'USERS__SORT_USER';
export const CHANGE_PAGE = 'USERS__CHANGE_PAGE';
export const CLEAR_SEARCH_FILTER = 'USERS__CLEAR_SEARCH_FILTER';
